/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package usp.each.dsid.ep1

import org.apache.spark.sql.SparkSession

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())
    val spark = SparkSession.builder()
      .appName("EP1-DSID")
      .master("local[*]")
      .getOrCreate()
    val instances = spark.read.csv("../EP1/google-traces/instance_events/*")
    instances.createOrReplaceTempView("instance")
    println(spark.sql("select avg(_c6) from instance").first())
  }

  def greeting(): String = "Hello, world!"
}
